name: Discord Notify on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord webhook embed notification
        uses: wei/curl@v1.3
        with:
          args: -H "Content-Type: application/json" -X POST -d '{
            "embeds": [
              {
                "title": "New update",
                "url": "https://niggas.bio",
                "color": 3066993,
                "description": "ðŸ§ƒ",
                "footer": {
                  "text": "niggas ðŸ§ƒ"
                }
              }
            ]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}